jefmsmit/gdshowsdb

data/gdshowsdb/song_refs.yaml
Issue #39 - 1991/12/30 - Missing Dear Prudence Jam after Saint
=> Change from "Dear Prudence" to "Dear Prudence Jam"

data/gdshowsdb/1991.yaml
1991/12/30 - Missing Dear Prudence Jam after Saint Issue #39
=> Fix issue #39

data/gdshowsdb/1971.yaml
Fix 1971/11/07 Missing Setlist #36
=> Fix 1971/11/07 Missing Setlist #36

data/gdshowsdb/1971.yaml
fix 1971/11/06 missing setlist #44
=> fix 1971/11/06 missing setlist #44

data/gdshowsdb/1971.yaml
fix 1971/11/11 missing setlist #46
=> fix 1971/11/11 missing setlist #46

data/gdshowsdb/1971.yaml
fix 1971/11/12 missing setlist #48
=> fix 1971/11/12 missing setlist #48

data/gdshowsdb/1971.yaml
fix 1971/11/14 missing setlist #50
=> fix 1971/11/14 missing setlist #50

data/gdshowsdb/1971.yaml
fix 1971/11/15 missing setlist #52
=> fix 1971/11/15 missing setlist #52

data/gdshowsdb/1971.yaml, data/gdshowsdb/1991.yaml
fixing a couple issues I noticed while migrating the data into a rails project using sqlite and rails 5.2.3
=> Fix jefmsmit/gdshowsdb#104 - Update the casing for Mr Mcgee and some alignment issues

data/gdshowsdb/1994.yaml, data/gdshowsdb/1995.yaml
Fix for the set list called out in #12
=> Fix 1995/02/21 set list

data/gdshowsdb/1971.yaml, data/gdshowsdb/song_refs.yaml
There were many gaps in 1971, this PR is to address the known ones.
Closes #24 
Closes #25 
Closes #36 
Closes #44
Closes #54 
Closes #56
Closes #57
Closes #58 
Closes #59 
Closes #60 
Closes #61
Closes #64
Closes #65 
Closes #66 
Closes #67 
Closes #68 
Closes #69 
Closes #70 
Closes #71 
Closes #72 
Closes #73 
Closes #74 
Closes #75
Closes #76 
Closes #77 
Closes #78 
Closes #79 
Closes #80 
Closes #81 
Closes #82 
Closes #83 
Closes #84 
Closes #85 
Closes #86 
Closes #87 
Closes #88 
Closes #89 
Closes #90
Closes #91 
Closes #92 
Closes #93 
Closes #94 
Closes #95 
Closes #96 
Closes #97 
Closes #98 
Closes #99 
Closes #100
=> 1971 cleanup

data/gdshowsdb/1985.yaml
Closes #14, adding segues to 1985-03-09
=> Closes #14, adding segues to 1985-03-09

data/gdshowsdb/1990.yaml
Closes #15 
Closes #16 
Closes #18
=> 1990 segues and space

data/gdshowsdb/1992.yaml
Closes #17, adds segues to 1992-03-20
=> Closes #17, adds segues to 1992-03-20

data/gdshowsdb/1969.yaml
=> closes #20, updates venue

data/gdshowsdb/1968.yaml
Closes #22, Closes #23. Updated DP 22 set lists
=> Closes #22, Closes #23. Updated DP 22 set lists

data/gdshowsdb/1991.yaml
Closes #26, segues for 1991-09-25
=> Closes #26, segues for 1991-09-25

data/gdshowsdb/1984.yaml
Closes #27, adding segues and space to 1984-04-26
=>  Closes #27, adding segues and space to 1984-04-26

data/gdshowsdb/1983.yaml
Closes #32, adds segues and missing NFA to 1983-04-12
=> Closes #32, adds segues and missing NFA to 1983-04-12

data/gdshowsdb/1980.yaml
Closes #34, set split and segues for 1980-10-03
=> Closes #34, set split and segues for 1980-10-03

data/gdshowsdb/1968.yaml, data/gdshowsdb/1969.yaml, data/gdshowsdb/1970.yaml, data/gdshowsdb/1971.yaml, data/gdshowsdb/1986.yaml, data/gdshowsdb/1991.yaml
- Added missing segued value for 1970/05/02 Morning Dew
- Fixed various format and spelling mistakes
=> Fix yaml formatting and spelling errors

data/gdshowsdb/1977.yaml
=> Remove empty songs collection for 1977/02/27
